### ISSUE TITLE
Feature Request: Setting Directory for Monorepo Setups

### ISSUE THREAD

**Issue by johannes-wtfoxtrot** [ralexander-phi/license_approval#9]
We'd like to use the action on a monorepo. However, I don't see any way to customize the directory in which `license_finder` should be executed.

It would be helpful, if the working directory could be customized with an additional input.

I could try opening a merge-request, if you are open to contributions.

Thanks for your time and support!

**Comment by ralexander-phi** [comment]
Hey, thanks for reaching out.

Yes, I'm supportive of that contribution. If you're able to open a pull request, I'll help get it merged in.

It's been a while since I've looked at this code myself, and I see that it really could use some tests and version updates. I'm going to try to get those added.

**Comment by chris-wtfoxtrot** [comment]
I've opened a pull request #13, so that a working directory can be stated.

**Comment by ralexander-phi** [comment]
Closed by #13
Thanks!
